language: java
before_script:
- echo "String build"
script:
- mvn clean package
after_script:
- echo "Script finished"
after success:
- echo "Build ready"
- ls -l $TRAVIS_BUILD_DIR/target
after_failure:
- echo "Build failure"
